-include .env
hardhat_build:
	npx hardhat compile

hardhat_test:
	npx hardhat test

hardhat_coverage:
	npx hardhat coverage

hardhat_clean:
	npx hardhat clean

hardhat_deploy_sepolia:
	npx hardhat ignition deploy ./ignition/modules/DeploySpacebear.js --network sepolia --verify